---
title: "moue_brain"
author: "songcheng"
date: "2022/8/3"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Mouse Brain

```{r}
library(SeuratDisk)
library(Seurat)
library(magrittr)
library(SPOTlight)
library(fda)
library(magrittr)
library(Seurat)
library(ggplot2)
library(RColorBrewer)
library(ggthemes)
library(Seurat)
#library(rcartocolors)
library(Spaniel)
library(FunSPOTlight)
library(magrittr)
library(dplyr)
library(glue) # 根据放入的变量生成图表标题
library(ggpubr) # 将图片保存为一个pdf文件
library(tidyverse)
library(scale)
library(ggsci)
```

## Load data

```{r}
setwd("D:\\research\\undergraduate\\fda_ST\\true_data\\mouse_brain_2\\sc_data")
seurat_obj=readRDS("seurat_obj.rds")
```


```{r}
#seurat_obj1$nnet2=seurat_obj1$liger_ident_coarse
data_counts = seurat_obj@assays$RNA@counts
  #data_counts <- data_counts[!duplicated(rownames(data_counts)), ]
  #data_counts=data_counts[sample(nrow(data_counts),round(0.5*nrow(data_counts))),]
  cell_type_factor = seurat_obj$liger_ident_coarse
  nnet2 = data.frame(cell_type_factor)
  colnames(nnet2) = "nnet2"
  rownames(nnet2) = colnames(data_counts)
  
  data = CreateSeuratObject(counts = data_counts,
                            assay = "RNA",
                            meta.data = nnet2)
  #data = data[, data$nnet2 %in% cell_type]
  clust_vr = "nnet2"
  seurat_obj=data
  rm(data)
  rm(data_counts)
Seurat::Idents(object = seurat_obj) <- seurat_obj@meta.data[, clust_vr]
seurat_obj=Seurat::SCTransform(seurat_obj)
marker_genes <- Seurat::FindAllMarkers(
                                     object = seurat_obj,
                                     verbose = TRUE,
                                     only.pos = TRUE,
                                     assay = "RNA",
                                     slot = "data")
```

```{r}
setwd("D:\\research\\undergraduate\\fda_ST\\true_data\\mouse_brain_2\\sc_data")
#saveRDS(marker_genes,"marker_genes_RNA.rds")
marker_genes=readRDS("marker_genes_RNA.rds")
```


```{r}
setwd("D:/research/undergraduate/fda_ST/true_data/mouse_brain/sc_data")
marker_genes=readRDS("marker_genes.rds")
```


```{r}
marker_gene_filt <- marker_genes %>% filter( pct.2 < 0.1)
marker_gene_filt %>% dplyr::count(cluster)
#marker_gene_filt=marker_genes
marker_gene_filt$cluster <- gsub(pattern = "[[:punct:]]|[[:blank:]]", ".", 
                                     x = marker_gene_filt$cluster, 
                                     perl = TRUE)
```

```{r}
clust_vr="nnet2"
cl_n=50
hvg=0
se_sc_down <- downsample_se_obj(
  se_obj = seurat_obj,
  clust_vr = clust_vr,
  cluster_markers = marker_gene_filt,
  cl_n = cl_n,
  hvg = hvg
)

getwd()
setwd("D:/research/undergraduate/fda_ST/true_data/mouse_brain/sc_data")
saveRDS(se_sc_down,"se_sc_down.rds")
```

```{r}
setwd("D:/research/undergraduate/fda_ST/true_data/mouse_brain_2/st")
#stdata=read.csv("Cerebellum_MappedDGEForR.csv")
st_loca=read.csv("Cerebellum_BeadLocationsForR.csv")

rownames(stdata)=stdata[,1]
stdata=stdata[,-1]
setwd("E:/research/undergraduate/fda_ST/true_data/mouse_brain_2/st")
#saveRDS(seurat_st,"seurat_st.rds")
#gene_name=readRDS("gene_name.rds")
seurat_st=createSeurat(counts = stdata,barcodeFile = "barcode.txt")
rm(stdata)
```

```{r}
setwd("E:/research/undergraduate/fda_ST/true_data/mouse_brain_2/st")
seurat_st=readRDS("seurat_st.rds")
```

#Downsample

```{r}
se_sc_down <- Seurat::SCTransform(object = se_sc_down)
# pdac_B <- Seurat::NormalizeData(object = pdac_B)
#se_sc_down <- Seurat::FindVariableFeatures(se_sc_down)
# pdac_B <- Seurat::ScaleData(pdac_A)
se_sc_down <- Seurat::RunPCA(se_sc_down, verbose = FALSE)
Seurat::ElbowPlot(se_sc_down, ndims = 50)
```


```{r}
se_sc_down=RunUMAP(se_sc_down,dims = 1:50)

```

## umap sc
```{r}

Idents(se_sc_down) <- se_sc_down$nnet2
umap_se_sc_down <- DimPlot(se_sc_down, reduction = "umap", group.by = "nnet2")+scale_color_ucscgb()
  umscale_color_npg()
scale_color_tableau()
scale_color_manual(values = as.character(df_col[as.character(df_col$plt_name) %in% cell_types, "col_ct"])) 
  #scale_color_tableau(palette = "Tableau 20")+
  #scale_x_discrete(breaks=NULL)+
  #scale_y_discrete(breaks=NULL)+
  #theme(axis.line = element_line(arrow = arrow(length = unit(0.5, 'cm'))))
  #theme(element_blank())
  #theme(axis.text.x = element_text(vjust=2))

print(umap_se_sc_down)


ggsave("umap_se_sc_down1.pdf",width = 10,height = 6)
```

```{r}
# setwd("E:/research/undergraduate/fda_ST/true_data/mouse_brain/ST_data/ST8059048/matrix")
# gene_name=read.csv2("features.tsv",sep="\t")
# gene_name=gene_name[,-3]
# gene_name_row=gene_name[,1]
# rownames(gene_name)=gene_name_row
# gene_name=as.matrix(gene_name[,-1])
# rownames(gene_name)=gene_name_row
 geno = as.matrix(se_sc_down@assays$RNA@counts)
 #geno=geno[rownames(geno)%in%rownames(gene_name),]
 #rownames(geno)=gene_name[rownames(geno),1]
 #marker_gene_filt$gene=gene_name[marker_gene_filt$gene,1]
 ST.matrix = seurat_st@assays$RNA@counts
 ST.matrix = as.matrix(ST.matrix)
 gene_name=rownames(geno)[rownames(geno)%in%rownames(seurat_st)]
 ST.matrix = ST.matrix[gene_name, ]
 geno=geno[rownames(ST.matrix),]
 cell.type.factor = se_sc_down$"nnet2"
```

#Deconvolution

```{r}
decon_mtrx = fun_spotlight2(
      geno = geno,
      ST.matrix = ST.matrix,
      cell.type.factor = cell.type.factor,
      nkonts = 300,
      nfpca=100,
      ct_mode = "median",
      cluster_marker = marker_genes,
      Upper_Bound = 10,
      Lower_Bound = 0.1
    )
    
    decon_mtrx = t(decon_mtrx)
    setwd("E:/research/undergraduate/fda_ST/true_data/mouse_brain_2")
    saveRDS(decon_mtrx,"decon_mtrx1.rds")
```

#Plot

```{r}
cell_types <- colnames(decon_mtrx)[! colnames(decon_mtrx) %in% "res_ss"]
cell_types <- gsub(pattern = "[[:punct:]]|[[:blank:]]", ".", 
                   x = cell_types, 
                   perl = TRUE)

qual_col_pals <- brewer.pal.info[brewer.pal.info$category == 'qual', ]
#qual_col_pals = qual_col_pals[qual_col_pals$colorblind==FALSE,]
#qual_col_pals=qual_col_pals[6:7,]
col_vector  <-  unlist(mapply(brewer.pal, qual_col_pals$maxcolors, rownames(qual_col_pals)))

col_vector =pal_ucscgb("default", alpha = 1)(26)
#col_vector1=c(1,2,4,5,6,7,8,9,11,13,15,16,17,19,20,21,22,25,26)
#col_vector=col_vector[col_vector1]
#col_vector=col_vector[seq(1:9)*2]
df_col <- data.frame(plt_name = cell_types,
                     df_name = gsub(pattern = "[[:punct:]]|[[:blank:]]", ".",
                                    x = cell_types,
                                    perl = TRUE),
                     col_ct = col_vector[1:length(cell_types)])
clust_vr="nnet2"
plt_names <- sort(unique(se_sc_down@meta.data[, clust_vr]))

df_plt_names <- data.frame(df_name = cell_types, 
                           plt_name = plt_names)
```


```{r}
dim(seurat_st)
index1=sample(ncol(seurat_st),3000)
index2=which(decon_mtrx[,ct]>0.5)
#index2=which(seurat_st@assays$RNA@counts[gene,]>0)
index=c(index1,index2)
index=unique(index)
seurat_st1=seurat_st[,index]
decon_mtrx1=decon_mtrx[index,]
```

```{r}
#index2=which(decon_mtrx[,ct]>0.5)
gene=gene_ct[gene_ct$cluster==ct,'gene'][10]
index2=which(seurat_st@assays$RNA@counts[gene,]>0)
index=c(index1,index2)
index=unique(index)
seurat_st1=seurat_st[,index]
decon_mtrx1=decon_mtrx[index,]
seurat_st1@assays$RNA@scale.data=as.matrix(seurat_st1@assays$RNA@data[gene_ct$gene,])
```

## gene types
```{r}
cluster_markers_a=marker_gene_filt

ct_gene_df <- lapply(unique(cluster_markers_a$cluster), function(clust) {
  ls1 <- cluster_markers_a[cluster_markers_a$cluster == clust, "gene"]
  ls2 <- cluster_markers_a[cluster_markers_a$cluster != clust, "gene"]
  ls1_unique <- ls1[! ls1 %in% ls2]

  return(cluster_markers_a[cluster_markers_a$cluster == clust & cluster_markers_a$gene %in% ls1_unique, ])
}) %>%
  bind_rows() %>%
  #filter(gene %in% rownames(se_sc_down)) %>% 
  group_by(cluster) %>% 
  arrange(cluster, p_val) %>% 
  # top_n(1) %>%
  filter(row_number() == 1) %>%
  data.frame()


gene_ct=cluster_markers_a[cluster_markers_a$gene%in%rownames(seurat_st),]
seurat_st1@assays$RNA@scale.data=as.matrix(seurat_st1@assays$RNA@data[gene_ct$gene,])
# setwd("E:/research/undergraduate/fda_ST/true_data/mouse_brain/ST_data/ST8059048/spatial")
# coor1=readRDS("coor1.rds")
# x=coor1[,1]
# y=coor1[,2]
 seurat_st$x=x/200
 seurat_st$y=y/200
# seurat_st$y=seurat_st$y-0.4
# seurat_st$x=seurat_st$x/1.1+0.5436364
# seurat_st$y=seurat_st$y/1.2+4.975995
ct=cell_types[14]
gene=gene_ct[gene_ct$cluster==ct,'gene'][10]
cell_types1=cell_types[cell_types%in%ct_gene_df$cluster]
gene_plt <- lapply(cell_types1, function(ct) {
    print(ct)
    ct_gene_df$cluster <- gsub(pattern = "[[:punct:]]|[[:blank:]]", ".", 
                                     x = ct_gene_df$cluster, 
                                     perl = TRUE)
    cell_types <- gsub(pattern = "[[:punct:]]|[[:blank:]]", ".", 
                                     x = cell_types, 
                                     perl = TRUE)
    ct <- gsub(pattern = "[[:punct:]]|[[:blank:]]", ".", 
                                     x = ct, 
                                     perl = TRUE)
    
    #seurat_st$x=seurat_st$x-min(seurat_st$x)
    #seurat_st$y=seurat_st$y-min(seurat_st$y)
    gene <- ct_gene_df[ct_gene_df$cluster == ct, "gene"]
    print(gene)
    
    tmp_plt <- spanielPlot(object = seurat_st1,
            grob = seurat_st1@images[[1]],
            plotType = "Gene",
            gene = gene,
            ptSizeMax = 5, 
            ptSizeMin = 0,
            customTitle = sprintf("Expression of: %s",  gene)) +
      theme_classic() +
      #xscale(2147,15975)+
      theme(
        plot.title = element_text(hjust = 0.5, size = 10),
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        axis.title = element_blank(),
        axis.line = element_blank(),
        legend.title = element_text(size=15),
      legend.text = element_text(size=15)
    ) +
      scale_color_gradientn(
        colours = wesanderson::wes_palette("Zissou1", 100,type = "continuous"))
    guides(color=guide_legend(override.aes = list(size=15)))
        
    tmp_plt

  })
```

```{r}
x=as.numeric(seurat_st$x)
y=as.numeric(seurat_st$y)
decon_df=cbind(decon_mtrx,as.matrix(x))
decon_df=cbind(decon_df,as.matrix(y))
decon_df=data.frame(decon_df,row.names = seq(1:nrow(decon_df)))
decon_mtrx1=data.frame(decon_mtrx)
colnames(decon_df)=c(colnames(decon_mtrx1),"x","y")
#decon_col_sum=apply(decon_mtrx, 2, sum)
#decon_df[,decon_col_sum!=0]
locaid=sample(seq(1:nrow(decon_mtrx)),2000)
decon_df=decon_df[locaid,]
#decon_df1=decon_df[c,]
library(ggthemes)
library(scatterpie)
plt=ggplot()+
  geom_scatterpie(data = decon_df,
                  aes(x,y,r=15),
                  cols = colnames(decon_df)[1:19])+
  scale_y_reverse()+
theme_classic()  +
  #scale_colour_calc()
  scale_fill_manual(values = as.character(df_col[as.character(df_col$plt_name) %in% cell_types, "col_ct"]))
  scale_fill_manual(values = colorRampPalette(brewer.pal(59, "Pastel2"))(59))
  print(plt)
setwd("E:/research/undergraduate/fda_ST/true_data/mouse_brain_2")
ggexport(plt,"scatterpie_plot.pdf")
ggsave("scatterpie_plot.pdf",width = 10,height = 6)
plt
```

```{r}
ct=cell_types[2]
ct_true=decon_df[,ct]>0.5
decon_df1=decon_df[ct_true,]
decon_df1=decon_df1[,apply(as.matrix(decon_df1), 2, sum)>1]
library(ggthemes)
library(scatterpie)
length(colnames(decon_df1))
plt=ggplot()+
  geom_scatterpie(data = decon_df1,
                  aes(x,y,r=0.3),
                  cols = colnames(decon_df1)[1:(ncol(decon_df1)-2)])+
  scale_y_reverse()+
theme_classic()  +
  #scale_colour_calc()
  scale_fill_manual(values = as.character(df_col[as.character(df_col$plt_name) %in% cell_types, "col_ct"]))
  scale_fill_manual(values = colorRampPalette(brewer.pal(59, "Pastel2"))(59))
```



```{r}
#a=x<5000
#b=y<5000

#a=as.logical(a)
#b=as.logical(b)
#a=as.list(a)
#b=as.list(b)
#a=as.data.frame(a)
#b=as.data.frame(b)
#d=cbind(matrix(a,nrow = length(a)),matrix(b,nrow = length(b)))
c=rep(TRUE,length(x))
for (i in 1:length(a)) {
  if(x[i]<7000){
    if(y[i]<7000){
    c[i]=TRUE
    }else{
    c[i]=FALSE
  }
  }else{
    c[i]=FALSE
  }
}
x_sub=x[c]
y_sub=y[c]
```


## cell types
```{r}
setwd("D:/research/undergraduate/fda_ST/true_data/mouse_brain_2")
 image=Spaniel::parseImage("white1.jpg")
 seurat_st@images=list(image)
#decon_mtrx=decon_mtrx[colnames(seurat_st),]
rownames(decon_mtrx) <- rownames(seurat_st@meta.data)
colnames(decon_mtrx) <- gsub(pattern = "[[:punct:]]|[[:blank:]]", ".", 
                                  x = colnames(decon_mtrx), 
                                  perl = TRUE)
seurat_st1@assays$RNA@scale.data <- t(decon_mtrx1)
#seurat_st@assays$RNA@data <- t(decon_mtrx)
decon_mtrx1=as.data.frame(decon_mtrx)
x=as.numeric(seurat_st$x)
y=as.numeric(seurat_st$y)

seurat_st$x=x
seurat_st$y=y
#seurat_st=seurat_st[,seurat_st$x>4.5]
#seurat_st=seurat_st[,seurat_st$x<28]
#seurat_st=seurat_st[,seurat_st$y>5]
#seurat_st=seurat_st[,seurat_st$y>24.5]
#decon_mtrx=decon_mtrx[colnames(seurat_st1),]
#seurat_st1=seurat_st[,seurat_st$nCount_RNA>500]
seurat_st1=seurat_st[,seurat_st$x<18|seurat_st$y<48]
ct_plt <- lapply(cell_types, function(ct){
  ct <- gsub(pattern = "[[:punct:]]|[[:blank:]]", ".", 
             x = ct, 
             perl = TRUE)
  print(ct)
  
  #image4=Spaniel::parseImage("fn_image4.jpg")
  #image2=Spaniel::parseImage("fn_image2.jpg")
  #st_se@images <- list(image1,image2,image3,image4)
  #st_se$y=(st_se$y/max(st_se$y))*30
  #st_se$x=(st_se$x/max(st_se$x))*30
  
  
  
  tmp_plt <- spanielPlot(object = seurat_st1,
                         grob = seurat_st1@images[[1]],
                         plotType = "Gene",
                         gene = ct,
                         ptSizeMax = 0.2, 
                         ptSizeMin = 0,
                         customTitle = sprintf(" Proportion of cell type: %s",ct)) +
    #geom_point(aes(alpha = ct)) +
    theme_classic() +
    theme(
      plot.title = element_text(hjust = 0.5, size = 10),
      axis.ticks = element_blank(),
      axis.text = element_blank(),
      axis.title = element_blank(),
      axis.line = element_blank(),
      legend.title = element_text(size=10),
      legend.text = element_text(size=10)
    ) +
    guides(color=guide_legend(override.aes = list(size=5)))+
    #scale_color_gradientn(colours = heat.colors(10, rev = TRUE),
    #                      limits = c(0, 1), name = "Proportion") +
    #scale_size_continuous(limits = c(0, 1), name = "Proportion")
    scale_color_gradientn(
        colours = wesanderson::wes_palette("Zissou1", 3,type = "continuous"),
        name = "Proportion",limits = c(0, 1)) +
    scale_size_continuous(limits = c(0, 1), name = "Proportion",range = c(0,1))
  
  
    #scale_x_continuous(limits = c(4.5,28))+
    #scale_y_continuous(limits = c(15,30))
  
  # print(tmp_plt)
  
  # ggsave(
  #   filename = sprintf("Proportion of cell type: %s", ct),
  #   device = "png",
  #   width = 8.56,
  #   height = 8
  # )
  return(tmp_plt)
})
```

```{r}
decon_df_ct=data.frame(matrix(rep(0,nrow(decon_mtrx)*3),nrow = nrow(decon_mtrx)))
rownames(decon_df_ct)=rownames(decon_mtrx)
colnames(decon_df_ct)=c('cell_types','x','y')
decon_df_ct$cell_types=colnames(decon_mtrx)[apply(decon_mtrx,1,which.max)]
decon_df_ct$x=x
decon_df_ct$y=y

ct_attention=cell_types[table(decon_df_ct$cell_types)>1500]
ct_attention=c(ct_attention,cell_types[18])
decon_df_ct1=decon_df_ct[decon_df_ct$cell_types%in%ct_attention,]
#decon_df_ct1=decon_df_ct1[sample(nrow(decon_df_ct1),10000),]
ct_color=c(1,2,13,4,5,6,7,8,16,11,12,18)
p1=ggplot()+
  geom_point(data = decon_df_ct1,
             aes(x,y,col =cell_types),size=0.01)+
  scale_y_reverse()+
theme_classic()  + 
  guides(color=guide_legend(override.aes = list(size=5)))+
  theme(
       plot.title = element_text(hjust = 0.5, size = 1),
       axis.text = element_blank(),
       axis.title = element_blank()
       ) +
  scale_color_manual(values = as.character(df_col[ct_color, "col_ct"]))
  scale_color_ucscgb()
  scale_color_tableau()
  scale_fill_manual(values = as.character(df_col[as.character(df_col$plt_name) %in% cell_types, "col_ct"]))
  scale_color_tableau()
  scale_color_hue()
  scale_color_brewer(palette="PRGn")
  scale_fill_manual(values = colorRampPalette(brewer.pal(9, "Paired"))(9))
  scale_color_brewer(palette="Paired")
  scale_color_tableau()
  scale_color_futurama()
  scale_fill_tron()
  scale_fill_manual(values = as.character(df_col[as.character(df_col$plt_name) %in% cell_types, "col_ct"]))
  scale_color_startrek()
  scale_color_uchicago()
  scale_color_ucscgb()PRGn
  scale_color_lancet()
  scale_color_npg(alpha = 0.6)
  scale_colour_calc()
  
  #scale_colour_calc()
  scale_fill_manual(values = as.character(df_col[as.character(df_col$plt_name) %in% cell_types, "col_ct"]))

```


```{r}
setwd("E:/research/undergraduate/fda_ST/true_data/mouse_brain_2/sc_data")
saveRDS(seurat_obj,"seurat_obj1.rds")
saveRDS(se_sc_down,"se_sc_down.rds")
```

```{r}
setwd("D:/research/undergraduate/fda_ST/true_data/mouse_brain_2")
ggexport(plotlist = ct_plt, filename = 'ct_plot.pdf')
#ggsave(ct_plt,"ct_plt.pdf")
```


```{r}
library(glue) # 根据放入的变量生成图表标题
library(ggpubr) # 将图片保存为一个pdf文件
library(tidyverse) # map2函数用于循环

# mtcars为示例数据
x = names(ct_plt)[1]
y = names(mtcars)[-1]


plot_list = map2(x, y, 
     ~ mtcars %>% 
       ggplot(aes_string(x = .x, y = .y)) +
       geom_point()+
       labs(title = glue('{.x} ~ {.y}')))
ct_plt1=ct_plt[1:16]
ggexport(plotlist = ct_plt, filename = 'plot1.pdf')
```


```{r}
library(ggpubr)
ct_plt1=ct_plt[1:8]
a=ggarrange(ct_plt[[1]],
            ct_plt[[2]],
            ct_plt[[3]],
            ct_plt[[4]],
            ct_plt[[5]],
            ct_plt[[6]],
            ct_plt[[7]],
            ct_plt[[8]],ncol = 4)
pdf("plots.pdf", onefile = TRUE,width = 1800,height = 400)
#print(a)
dev.off()
print(ct_plt[[1]])
print(ct_plt[[2]])
ggexport("test.pdf",a)

for (i in seq(length(ct_plt))) {
  do.call("grid.arrange", ct_plt[[i]])  
}
ggsave("test.pdf", do.call("marrangeGrob", c(unlist(ct_plt,recursive=FALSE),nrow=2,ncol=1)))
dev.off()
```


## scatterpie plot
```{r}
x=seurat_st$x
y=seurat_st$y
decon_df=cbind(decon_mtrx,as.matrix(x))
decon_df=cbind(decon_df,as.matrix(y))
decon_df=data.frame(decon_df,row.names = seq(1:nrow(decon_df)))
decon_mtrx1=data.frame(decon_mtrx)
colnames(decon_df)=c(colnames(decon_mtrx1),"x","y")
#decon_col_sum=apply(decon_mtrx, 2, sum)
#decon_df[,decon_col_sum!=0]

decon_df1=decon_df[1:1000,]
library(ggthemes)
library(scatterpie)
plt=ggplot()+
  geom_scatterpie(data = decon_df,
                  aes(x,y,r=0.3),
                  cols = colnames(decon_df)[1:59])+
  scale_y_reverse()+
theme_classic()  +
  #scale_colour_calc()
  scale_fill_manual(values = colorRampPalette(brewer.pal(59, "Pastel2"))(59))


plt
```

```{r}
for (i in 1:length(cell_types)) {
  seurat_st[[cell_types[i]]] <- decon_mtrx[,cell_types[i]]
}
```


```{r}
#rownames(decon_mtrx)
decon_mtrx2=t(decon_mtrx)
names(decon_mtrx2)=rownames(decon_mtrx2)
#seurat_st[["cell_types"]]=decon_mtrx2
cell_type_prop_list=list()
for (i in 1:ncol(decon_mtrx2)) {
  cell_type_prop_list[[colnames(decon_mtrx2)[i]]]=decon_mtrx2[,i]
}
names(cell_type_prop_list)
seurat_st[["cell_types"]]=cell_type_prop_list
```


```{r}
pt1 <- Spaniel::spanielPlot(object = seurat_st,
                     grob = seurat_st@images[[1]], 
                     plotType = "Cluster",
                     clusterRes = cell_types[[55]],
                     ptSize = 1) +
  theme_void() +
  coord_fixed(1) +
  scale_alpha(range = c(1, 1)) +
  scale_color_gradientn(
        colours = wesanderson::wes_palette("Zissou1", 100, type = "continuous"))
pt1
```



```{r}

ct_plt2=spanielPlot(object = seurat_st,
            grob = seurat_st@images[[1]],
            plotType = "cluster",
            gene = gene,
            ptSizeMax = 2, 
            ptSizeMin = 0,
            customTitle = sprintf("Expression of: %s",  gene)) +
      theme_classic() +
      #xscale(2147,15975)+
      theme(
        plot.title = element_text(hjust = 0.5, size = 10),
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        axis.title = element_blank(),
        axis.line = element_blank(),
        legend.title = element_text(size=15),
      legend.text = element_text(size=15)
    ) +
    guides(color=guide_legend(override.aes = list(size=15)))
```

```{r}
x=seurat_st$x
y=seurat_st$y
decon_df=cbind(decon_mtrx,as.matrix(x))
decon_df=cbind(decon_df,as.matrix(y))
decon_df=data.frame(decon_df,row.names = seq(1:nrow(decon_df)))
decon_mtrx1=data.frame(decon_mtrx)
colnames(decon_df)=c(colnames(decon_mtrx1),"x","y")
setwd("D:/research/undergraduate/fda_ST/true_data/mouse_brain/ST_data/ST8059048/spatial")
p=plot_image("image.jpg")
```

```{r}
decon_df=data.frame(matrix(rep(0,nrow(decon_mtrx)*3),ncol = 3))
colnames(decon_df)=c("cell_types","x","y")
for (i in 1:nrow(decon_df)) {
  decon_df[i,1]=cell_types[which.max(decon_mtrx[i,])]
}
rownames(decon_df)=c(1:nrow(decon_df))
decon_df[,2]=x
decon_df[,3]=y
```



```{r}
p1=ggplot(data=decon_df,aes(x=x,y=y,color=cell_types))+
  geom_point()+
  scale_color_manual(values = as.character(df_col[as.character(df_col$plt_name) %in% cell_types, "col_ct"])) 
```







